### ISSUE TITLE
[DATA] normalize/rescale ML electricity access data layers

### ISSUE THREAD

**Issue by iferencik** [UNDP-Data/geohub#2463]
### Issue Description

The ML layers are not well designed and feature some inherent internal inconsistencies (0-255 instead of 100), absolute average values per country, which make the dataset ill suited for analytics

### References

https://geohub.data.undp.org/data?queryoperator=and&operator=and&sortby=updatedat%2Cdesc&limit=10&offset=0&query=machine+electricity

### Dataset ID

https://geohub.data.undp.org/data/d338350b5f3536164fb3d1b71e6a85b5

Data per country is available at

https://undpngddlsgeohubdev01.blob.core.windows.net/hrea/MLEE/

hrea container

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1265112353) by [Unito](https://www.unito.io)

**Comment by JinIgarashi** [comment]
https://undp.sharepoint.com/:w:/r/sites/SDGIntegrationteam/Shared%20Documents/SDG%20Metrics,%20Data%20and%20Analytics/4.%20Projects/Geohub/0.%20Storage/GeoHub_GIS%20Data%20Storage/Electricity%20Mapping/Archive/Electricity%20Mapping.docx?d=wa4830e2d2a3746cc865693f9f4b9b1b6&csf=1&web=1&e=kMXo6D

**Comment by JinIgarashi** [comment]
I tried to fix the issue in the repo (https://github.com/UNDP-Data/geo-ml-electricity-acess-processing).

But rescaled to 0-100, but could not solve the issue properly.

**Comment by JinIgarashi** [comment]
I have tried to normalize ML data in https://github.com/UNDP-Data/geo-ml-electricity-acess-processing, but it was not easy since the current data is really bad quality and we are missing original datasets for it.

so, we decided to remove ML data from Electricity Dashboard, and also delete them from GeoHub once new electricity dashboard will be merged to production. so this issue is no longer needed.
