### ISSUE TITLE
[UI/UX] redesign settings page

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#2876]
current setting page

![image](https://github.com/UNDP-Data/geohub/assets/2639701/b4faaa3b-2aa7-4ff3-9764-618ceb4349e5)

I think we can use the same tabs design in maps page and data page for settings, it will be more compact and more unified design.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1302954684) by [Unito](https://www.unito.io)

**Comment by balagurova** [comment]
Hi @JinIgarashi 
Getting back to you with the settings mockup. I think your idea about using tabs to align page layouts was a good one! However, instead of the accordion, I suggest using a sticky sidebar to provide navigation between different sections of the settings.

For example, under the 'Map' tab, there is a sidebar with the items: 'Map layout', 'Search', etc. By clicking on each sidebar item, the user will be navigated (through the anchor links) to the particular section in the settings. Since the sidebar is sticky, the user will always have this navigation, which might be handy.

[The mockup can be found here](https://www.figma.com/file/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?type=design&node-id=3070-3492&mode=design)

Few important notes:
1) A sidebar style can be taken from this page: https://www.undp.org/procurement 
2) Let's adjust the spacing between the text elements to visually group them together. Providing a quick image since you don't have access to figma's dev mode:
<img width="1225" alt="image" src="https://github.com/UNDP-Data/geohub/assets/73748770/2ddd098a-5627-48eb-a034-c13671b27728">

**Comment by JinIgarashi** [comment]
Sidebar for UNDP design system

https://design.undp.org/?path=/docs/components-navigation-components-sidebar--docs
