### ISSUE TITLE
[UI/UX] storymap initial setup

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#3869]
### Description

to avoid showing error message, maybe title and basemap selector can remain at initial setup dialog.

## current UI

first setup

![image](https://github.com/user-attachments/assets/9f78fba8-17dc-4668-98e4-e22bd6ae7929)

after that,

![image](https://github.com/user-attachments/assets/5db2b616-1cd7-4799-9d81-a97745f1ec1b)

**Comment by balagurova** [comment]
[Figma prototype with the storymap setup](https://www.figma.com/design/xPemdxTmvPi2homUZ2dyw0/UNDP-GeoHub-UI?node-id=3480-5438&t=UONgKBfBOy96YQqK-1)

**Comment by balagurova** [comment]
Please add a default title so that there is no error in the initial state

**Comment by balagurova** [comment]
I noticed that the default title is 'Untitle.' Could you please confirm if this is intentional, or if it should be 'Untitled'? If it's a typo, could you update it to 'Untitled'?
<img width="729" alt="image" src="https://github.com/user-attachments/assets/87560787-9a2f-4175-b985-d4773f5dd146">

I also recommend allowing the option to save a storymap with just a cover slide. Currently, it's unclear why the 'Save' button is inactive. If there's a specific reason why the storymap can't be saved without at least one slide, could we add a tooltip on hover to explain why the button isn't active and what needs to be done to enable it? This would improve clarity for users.
